export const workProjects = [
  {
    id: 'ihss',
    title: 'Indian Healthy Snacking Summit',
    subtitle: '1.0 & 2.0 — Branding, report writing, end-to-end ownership',
    tags: ['Brand Identity', 'Editorial', 'Event'],
    href: '/work/ihss',
    image: null,
    comingSoon: false,
    external: null,
  },
  {
    id: 'blinkit',
    title: 'Blinkit × Farmley Page Takeover',
    subtitle: 'Brand campaign, twice',
    tags: ['Brand Campaign', 'D2C'],
    href: '/work/blinkit',
    image: null,
    comingSoon: false,
    external: null,
  },
  {
    id: 'recipe',
    title: 'Recipe Website',
    subtitle: 'Built with Cursor, Claude, Tailwind, React, Supabase',
    tags: ['Code', 'Side Project', 'React'],
    href: '/work/recipe',
    image: null,
    comingSoon: false,
    external: null,
  },
  {
    id: 'mito',
    title: 'Mito Health',
    subtitle: 'Product design for a health-tech platform',
    tags: ['Product Design', 'UX'],
    href: null,
    image: null,
    comingSoon: true,
    external: null,
  },
  {
    id: 'branding',
    title: 'Branding Collection',
    subtitle: 'Brand identity work across industries',
    tags: ['Branding', 'Identity'],
    href: null,
    image: null,
    comingSoon: false,
    external: 'https://behance.net',
  },
]
